import './js/header';
import './js/hero';
import '.js/about';
import './js/benefits';
import './js/projects';
import './js/faq';
import './js/coversr';
import './js/reviews';
import './js/work-together';
